#!/usr/bin/env bash
# reorganize_data.sh — group the Methane_AMMBEC folder by instrument, and park
# everything redundant in _to_delete_ (nothing is ever deleted by this script).
#
#   cd ~/Downloads/Methane_AMMBEC/methane_AMMBEC
#   bash reorganize_data.sh          # show what would move, change nothing
#   bash reorganize_data.sh --apply  # do it
#
# Resulting layout (run_local.sh already points at it):
#
#   instruments/Aircraft/        NOAA Twin Otter ICARTT  (name fixed: R/paths.R looks
#                                for <DATA_DIR>/Aircraft)
#   instruments/ARC/             NOAA ARL Air Resources Car, daily zips
#   instruments/MobileLab/       NOAA CSL Mobile Lab, 2024-07-09
#   instruments/MOOSE/           CDPHE MOOSE van, daily zips
#   instruments/CDPHE_mobile/    CDPHE CAT/EMU quarterly methane surveys
#   instruments/Lidar_Dalek2/    Doppler lidar, DSRC Boulder — the pair the paper uses
#   instruments/Lidar_PUMAS/     Doppler lidar, truck (June DSRC, July DJ Basin)
#   instruments/TOPAZ/           TOPAZ site surface in-situ record
#   instruments/docs/            campaign PDFs
#   inventories/GRA2PES/  /Vulcan/  /EPA_GHGI/   + NEI zip and metro outline at its root
#   manuscript/                  paper, SI, toxics paper, the email thread
#   outputs/                     pipeline outputs (regenerated by run_local.sh)
#   _to_delete_/                 duplicates and scratch — review, then delete by hand
#
# The two lidars publish files with IDENTICAL names from different places, which is
# why they get separate folders here; see REPRODUCTION_2026-09-11.md.
# -----------------------------------------------------------------------------
set -euo pipefail
cd "$(dirname "$0")"
BASE="${METHANE_BASE:-$(cd .. && pwd)}"
APPLY=0; [ "${1:-}" = "--apply" ] && APPLY=1
[ $APPLY -eq 1 ] || echo "DRY RUN — nothing will move. Re-run with --apply to do it."
echo "Base: $BASE"; echo

moved=0; skipped=0
# move <src> <dest-dir>: moves a file or directory's contents, never overwrites
mv_into() {
  local src="$1" dst="$2"
  [ -e "$src" ] || { skipped=$((skipped+1)); return 0; }
  echo "  $(basename "$src")  ->  ${dst#$BASE/}/"
  if [ $APPLY -eq 1 ]; then
    mkdir -p "$dst"
    if [ -d "$src" ]; then
      # move the directory's contents, so re-running is harmless
      find "$src" -mindepth 1 -maxdepth 1 -exec mv -n {} "$dst"/ \;
      rmdir "$src" 2>/dev/null || true
    else
      mv -n "$src" "$dst"/
    fi
  fi
  moved=$((moved+1))
}

I="$BASE/instruments"; INV="$BASE/inventories"; MS="$BASE/manuscript"; DEL="$BASE/_to_delete_"

echo "== instruments =="
mv_into "$BASE/Aircraft"      "$I/Aircraft"
mv_into "$BASE/MobileLab"     "$I/MobileLab"
mv_into "$BASE/MethaneData"   "$I/CDPHE_mobile"
mv_into "$BASE/Dalek"         "$I/Lidar_Dalek2"
mv_into "$BASE/Pumas"         "$I/Lidar_PUMAS"

# AMMBEC_2 is a mixed download folder: sort its daily zips by what is inside them.
if [ -d "$BASE/AMMBEC_2" ]; then
  for z in "$BASE/AMMBEC_2"/*.zip; do
    [ -e "$z" ] || continue
    names="$(unzip -Z1 "$z" 2>/dev/null || true)"
    case "$names" in
      *ARL-Suite_ARC*)   mv_into "$z" "$I/ARC" ;;
      *MobileLab*)       mv_into "$z" "$I/MobileLab/zips" ;;
      *MOOSE*)           mv_into "$z" "$I/MOOSE" ;;
      *)                 mv_into "$z" "$I/unsorted_zips" ;;   # empty or unrecognised
    esac
  done
  mv_into "$BASE/AMMBEC_2/TOPAZ_AMMBEC.rtf" "$I/TOPAZ"
  mv_into "$BASE/AMMBEC_2/AMMBEC 2024 NOAA Twin Otter Data Download By Submission.pdf" "$I/docs"
  # the velStats/windProf copies here are byte-for-byte the Pumas/Dalek files
  for f in velStats_202406.nc velStats_202407.nc windProf_202406.nc windProf_202407.nc; do
    mv_into "$BASE/AMMBEC_2/$f" "$DEL/AMMBEC_2_lidar_duplicates"
  done
  [ $APPLY -eq 1 ] && rmdir "$BASE/AMMBEC_2" 2>/dev/null || true
fi

echo
echo "== inventories =="
mv_into "$BASE/GRA2PES"    "$INV/GRA2PES"
mv_into "$BASE/GRA2PESv1.0_total_CO_202106.tif_undefined" "$INV/GRA2PES/v1.0_CO_tifs"
mv_into "$BASE/Vulcan_CO2" "$INV/Vulcan"
mv_into "$BASE/EPA_methane" "$INV/EPA_GHGI"
mv_into "$BASE/EmissionsInventory" "$INV"          # NEI zip + denver7_metro_outline.csv
mv_into "$BASE/GRA2PESv2.0_CONUS4km_grid_info.nc" "$DEL"   # duplicate of the copy in GRA2PES/

echo
echo "== manuscript =="
mv_into "$BASE/aircraft_methane_Denver.docx"    "$MS"
mv_into "$BASE/SI_aircraft_methane_denver.docx" "$MS"
mv_into "$BASE/Toxics-paper"                    "$MS/Toxics-paper"
mv_into "$BASE/Gmail - AiRMAPS methane data over Denver.pdf" "$MS"

echo
echo "== outputs =="
# MethaneData_outputs mixes two runs and holds a truncated mobile_hotspots.csv;
# run_local.sh regenerates everything into outputs/.
mv_into "$BASE/MethaneData_outputs" "$DEL/MethaneData_outputs_mixed_runs"
mv_into "$BASE/Claude outputs"      "$BASE/outputs/from_chat"

echo
echo "== _to_delete_ =="
for f in "$BASE/Aircraft"/*"(1)"*.ict.duplicate "$I/Aircraft"/*"(1)"*.ict.duplicate; do
  [ -e "$f" ] || continue
  mv_into "$f" "$DEL/duplicate_icartt"
done
mv_into "$BASE/MethaneData.zip" "$DEL"            # extracted into CDPHE_mobile
mv_into "$BASE/_to_delete"      "$DEL/old_scratch"
mv_into "$INV/GRA2PES/GRA2PESv1.0_total_CO_202106.tif_undefined.zip" "$DEL"  # tifs extracted

echo
echo "moved/would move: $moved   not present: $skipped"
if [ $APPLY -eq 1 ]; then
  echo
  echo "Now check the run still resolves:"
  for p in "$I/Aircraft" "$I/Lidar_Dalek2/velStats_202406.nc" "$I/MobileLab" \
           "$INV/EPA_GHGI" "$INV/Vulcan" "$I/CDPHE_mobile"; do
    [ -e "$p" ] && echo "  ok      ${p#$BASE/}" || echo "  MISSING ${p#$BASE/}"
  done
  echo
  echo "Then:  bash run_local.sh"
  echo "Review $DEL and delete it by hand when you are happy."
fi
